# Generated by Django 4.2.3 on 2023-07-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
