# Generated by Django 4.2.3 on 2023-07-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0002_todo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("option1", "Complete"), ("option2", "Incomplete")],
                max_length=50,
            ),
        ),
    ]
