# Generated by Django 4.2.3 on 2023-07-18 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0003_alter_todo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="expiry_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
