# Generated by Django 4.2.3 on 2023-07-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0004_todo_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
