# Generated by Django 4.2.3 on 2023-07-18 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0005_alter_todo_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
