# Generated by Django 4.2.3 on 2023-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0006_alter_todo_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
