# Generated by Django 4.2.3 on 2023-07-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0008_alter_todo_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
