# Generated by Django 4.2.3 on 2023-07-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0009_alter_todo_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="text",
            new_name="todoDetail",
        ),
    ]
